export const controlsConfig = {
  header: {
    chLetters: {
      section: "C and H Letters",
      properties: ["chGroupY", "cScale", "cX", "cY", "hScale", "hX", "hY"],
      defaults: {
        desktop: {
          chGroupY: 0.1,
          cScale: 0.0011,
          cX: -0.46,
          cY: 0.17,
          hScale: 0.0011,
          hX: -0.051,
          hY: 0.17,
        },
        tablet: {
          chGroupY: 0.1,
          cScale: 0.01,
          cX: -3.02,
          cY: 0.96,
          hScale: 0.01,
          hX: 0.08,
          hY: 0.96,
        },
        mobile: {
          chGroupY: 0.06,
          cScale: 0.01,
          cX: -0.8,
          cY: 0.8,
          hScale: 0.01,
          hX: -0.7,
          hY: -0.5,
        },
      },
      ranges: {
        chGroupY: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        cScale: {
          min: 0,
          max: 0.05,
          step: 0.001,
        },
        cX: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        cY: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        hScale: {
          min: 0,
          max: 0.05,
          step: 0.001,
        },
        hX: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        hY: {
          min: -5,
          max: 5,
          step: 0.01,
        },
      },
    },
  },
  content: {
    global: {
      section: "Global",
      properties: [
        "globalBorder",
        "globalButtonBorder",
        "headlineFont",
        "descFont",
        "moreButtonPaddingX",
        "moreButtonPaddingY",
        "globalFontColor",
        "globalBorderColor",
        "globalSvgColor",
      ],
      defaults: {
        desktop: {
          globalBorder: 0.004,
          globalButtonBorder: 0.005,
          headlineFont: 0.048,
          descFont: 0.016,
          moreButtonPaddingX: 0.4,
          moreButtonPaddingY: 0.18,
          globalFontColor: "#403454",
          globalBorderColor: "#403454",
          globalSvgColor: "#403454",
        },
        tablet: {
          globalBorder: 0.01,
          globalButtonBorder: 0.01,
          headlineFont: 0.045,
          descFont: 0.023,
          moreButtonPaddingX: 0.2,
          moreButtonPaddingY: 0.1,
          globalFontColor: "#38358f",
          globalBorderColor: "#38358f",
          globalSvgColor: "#38358f",
        },
        mobile: {
          globalBorder: 0.01,
          globalButtonBorder: 0.01,
          headlineFont: 0.045,
          descFont: 0.023,
          moreButtonPaddingX: 0.2,
          moreButtonPaddingY: 0.1,
          globalFontColor: "#38358f",
          globalBorderColor: "#38358f",
          globalSvgColor: "#38358f",
        },
      },
      ranges: {
        globalBorder: {
          min: 0,
          max: 0.1,
          step: 0.001,
        },
        globalButtonBorder: {
          min: 0,
          max: 0.1,
          step: 0.001,
        },
        headlineFont: {
          min: 0,
          max: 0.2,
          step: 0.001,
        },
        descFont: {
          min: 0,
          max: 0.2,
          step: 0.001,
        },
        moreButtonPaddingX: {
          min: 0,
          max: 1,
          step: 0.01,
        },
        moreButtonPaddingY: {
          min: 0,
          max: 1,
          step: 0.01,
        },
        globalFontColor: {
          min: "#000000",
          max: "#ffffff",
          step: "#000001",
        },
        globalBorderColor: {
          min: "#000000",
          max: "#ffffff",
          step: "#000001",
        },
        globalSvgColor: {
          min: "#000000",
          max: "#ffffff",
          step: "#000001",
        },
      },
    },
    introduction: {
      section: "Introduction",
      properties: ["introX", "introY", "introWidth"],
      defaults: {
        desktop: {
          introX: -2.46,
          introY: -0.65,
          introWidth: 0.52,
        },
        tablet: {
          introX: -3.02,
          introY: -0.65,
          introWidth: 0.52,
        },
        mobile: {
          introX: -3.02,
          introY: -0.65,
          introWidth: 0.52,
        },
      },
      ranges: {
        introX: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        introY: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        introWidth: {
          min: 0,
          max: 3,
          step: 0.01,
        },
      },
    },
    work1: {
      section: "Work 1",
      properties: [
        "w1ImgX",
        "w1Y",
        "w1TitleX",
        "w1TitleY",
        "w1TitleWidth",
        "w1DescX",
        "w1DescY",
        "w1DescWidth",
        "w1ImgScaleX",
        "w1ImgScaleY",
        "w1MoreX",
        "w1MoreY",
        "w1MoreScale",
      ],
      defaults: {
        desktop: {
          w1ImgX: -0.13,
          w1Y: -1.02,
          w1TitleX: 0.99,
          w1TitleY: -0.89,
          w1TitleWidth: 0.2,
          w1DescX: 0.97,
          w1DescY: -1.01,
          w1DescWidth: 0.28,
          w1ImgScaleX: 1.91,
          w1ImgScaleY: 1.23,
          w1MoreX: 1.12,
          w1MoreY: -1.16,
          w1MoreScale: 0.56,
        },
        tablet: {
          w1ImgX: -0.13,
          w1Y: -1.19,
          w1TitleX: 1.55,
          w1TitleY: -1,
          w1TitleWidth: 0.2,
          w1DescX: 0.77,
          w1DescY: -0.53,
          w1DescWidth: 1.3,
          w1ImgScaleX: 1.5,
          w1ImgScaleY: 0.9,
          w1MoreX: -0.35,
          w1MoreY: -0.2,
          w1MoreScale: 0.8,
        },
        mobile: {
          w1ImgX: -0.13,
          w1Y: -1.02,
          w1TitleX: -0.63,
          w1TitleY: -1.7,
          w1TitleWidth: 0.24,
          w1DescX: 1,
          w1DescY: -0.81,
          w1DescWidth: 1,
          w1ImgScaleX: 1.5,
          w1ImgScaleY: 0.9,
          w1MoreX: -0.35,
          w1MoreY: -0.2,
          w1MoreScale: 0.8,
        },
      },
      ranges: {
        w1ImgX: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        w1Y: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        w1TitleX: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        w1TitleY: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        w1TitleWidth: {
          min: 0,
          max: 3,
          step: 0.01,
        },
        w1DescX: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        w1DescY: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        w1DescWidth: {
          min: 0,
          max: 3,
          step: 0.01,
        },
        w1ImgScaleX: {
          min: 0,
          max: 3,
          step: 0.01,
        },
        w1ImgScaleY: {
          min: 0,
          max: 3,
          step: 0.01,
        },
        w1MoreX: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        w1MoreY: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        w1MoreScale: {
          min: 0,
          max: 2,
          step: 0.01,
        },
      },
    },
    work2: {
      section: "Work 2",
      properties: [
        "w2ImgX",
        "w2Y",
        "w2TitleX",
        "w2TitleY",
        "w2TitleWidth",
        "w2DescX",
        "w2DescY",
        "w2DescWidth",
        "w2ImgScaleX",
        "w2ImgScaleY",
        "w2MoreX",
        "w2MoreY",
        "w2MoreScale",
      ],
      defaults: {
        desktop: {
          w2ImgX: 0.38,
          w2Y: -1.45,
          w2TitleX: -2.2,
          w2TitleY: -1.32,
          w2TitleWidth: 0.19,
          w2DescX: -2.21,
          w2DescY: -1.45,
          w2DescWidth: 0.25,
          w2ImgScaleX: 1.83,
          w2ImgScaleY: 1.17,
          w2MoreX: -1.92,
          w2MoreY: -1.61,
          w2MoreScale: 0.8,
        },
        tablet: {
          w2ImgX: 0.38,
          w2Y: -1.45,
          w2TitleX: -2.2,
          w2TitleY: -1.32,
          w2TitleWidth: 1,
          w2DescX: -1.2,
          w2DescY: -0.75,
          w2DescWidth: 1.3,
          w2ImgScaleX: 1.2,
          w2ImgScaleY: 0.9,
          w2MoreX: -2.2,
          w2MoreY: -0.2,
          w2MoreScale: 0.8,
        },
        mobile: {
          w2ImgX: 0.38,
          w2Y: -1.82,
          w2TitleX: -0.57,
          w2TitleY: -2.14,
          w2TitleWidth: 0.65,
          w2DescX: -0.4,
          w2DescY: -1.1,
          w2DescWidth: 0.8,
          w2ImgScaleX: 1.2,
          w2ImgScaleY: 0.9,
          w2MoreX: -2.2,
          w2MoreY: -0.2,
          w2MoreScale: 0.8,
        },
      },
      ranges: {
        w2ImgX: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        w2Y: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        w2TitleX: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        w2TitleY: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        w2TitleWidth: {
          min: 0,
          max: 3,
          step: 0.01,
        },
        w2DescX: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        w2DescY: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        w2DescWidth: {
          min: 0,
          max: 3,
          step: 0.01,
        },
        w2ImgScaleX: {
          min: 0,
          max: 3,
          step: 0.01,
        },
        w2ImgScaleY: {
          min: 0,
          max: 3,
          step: 0.01,
        },
        w2MoreX: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        w2MoreY: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        w2MoreScale: {
          min: 0,
          max: 2,
          step: 0.01,
        },
      },
    },
    work3: {
      section: "Work 3",
      properties: [
        "w3ImgX",
        "w3Y",
        "w3TitleX",
        "w3TitleY",
        "w3TitleWidth",
        "w3DescX",
        "w3DescY",
        "w3DescWidth",
        "w3ImgScaleX",
        "w3ImgScaleY",
        "w3MoreX",
        "w3MoreY",
        "w3MoreScale",
      ],
      defaults: {
        desktop: {
          w3ImgX: -0.75,
          w3Y: -1.83,
          w3TitleX: 0.2,
          w3TitleY: -1.75,
          w3TitleWidth: 0.24,
          w3DescX: 0.21,
          w3DescY: -1.93,
          w3DescWidth: 0.21,
          w3ImgScaleX: 1.76,
          w3ImgScaleY: 1.11,
          w3MoreX: 1.13,
          w3MoreY: -2.01,
          w3MoreScale: 0.8,
        },
        tablet: {
          w3ImgX: 0.38,
          w3Y: -1.85,
          w3TitleX: 0.2,
          w3TitleY: -1.75,
          w3TitleWidth: 1,
          w3DescX: 0.1,
          w3DescY: -0.97,
          w3DescWidth: 1.3,
          w3ImgScaleX: 1.2,
          w3ImgScaleY: 0.9,
          w3MoreX: -2.2,
          w3MoreY: -0.2,
          w3MoreScale: 0.8,
        },
        mobile: {
          w3ImgX: 0.38,
          w3Y: -2.67,
          w3TitleX: -0.78,
          w3TitleY: -2.95,
          w3TitleWidth: 1,
          w3DescX: -0.44,
          w3DescY: -1.56,
          w3DescWidth: 1,
          w3ImgScaleX: 1.2,
          w3ImgScaleY: 0.9,
          w3MoreX: -2.2,
          w3MoreY: -0.2,
          w3MoreScale: 0.8,
        },
      },
      ranges: {
        w3ImgX: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        w3Y: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        w3TitleX: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        w3TitleY: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        w3TitleWidth: {
          min: 0,
          max: 3,
          step: 0.01,
        },
        w3DescX: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        w3DescY: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        w3DescWidth: {
          min: 0,
          max: 3,
          step: 0.01,
        },
        w3ImgScaleX: {
          min: 0,
          max: 3,
          step: 0.01,
        },
        w3ImgScaleY: {
          min: 0,
          max: 3,
          step: 0.01,
        },
        w3MoreX: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        w3MoreY: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        w3MoreScale: {
          min: 0,
          max: 2,
          step: 0.01,
        },
      },
    },
    playground: {
      section: "Playground",
      properties: [
        "playX",
        "playY",
        "playHeaderFont",
        "playMoreX",
        "playMoreY",
        "playMoreScale",
        "playBorderWidth",
        "playBorderHeight",
        "playBorderX",
        "playBorderY",
      ],
      defaults: {
        desktop: {
          playX: 0.42,
          playY: -2.43,
          playHeaderFont: 0.108,
          playMoreX: -1.03,
          playMoreY: -0.09,
          playMoreScale: 0.69,
          playBorderWidth: 3.7,
          playBorderHeight: 1.7,
          playBorderX: -0.41,
          playBorderY: 0.17,
        },
        tablet: {
          playX: 0.1,
          playY: -2.5,
          playHeaderFont: 0.08,
          playMoreX: -0.35,
          playMoreY: -0.2,
          playMoreScale: 0.8,
          playBorderWidth: 2.8,
          playBorderHeight: 1.7,
          playBorderX: 0,
          playBorderY: 0,
        },
        mobile: {
          playX: 0.1,
          playY: -2.5,
          playHeaderFont: 0.08,
          playMoreX: -0.35,
          playMoreY: -0.2,
          playMoreScale: 0.8,
          playBorderWidth: 2.8,
          playBorderHeight: 1.7,
          playBorderX: 0,
          playBorderY: 0,
        },
      },
      ranges: {
        playX: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        playY: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        playHeaderFont: {
          min: 0,
          max: 0.2,
          step: 0.001,
        },
        playMoreX: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        playMoreY: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        playMoreScale: {
          min: 0,
          max: 2,
          step: 0.01,
        },
        playBorderWidth: {
          min: 0.5,
          max: 5,
          step: 0.1,
        },
        playBorderHeight: {
          min: 0.5,
          max: 3,
          step: 0.1,
        },
        playBorderX: {
          min: -2,
          max: 2,
          step: 0.01,
        },
        playBorderY: {
          min: -2,
          max: 2,
          step: 0.01,
        },
      },
    },
    contact: {
      section: "Get in Contact",
      properties: [
        "conX",
        "conY",
        "conButtonX",
        "conButtonY",
        "conButtonScale",
        "conButtonPaddingX",
        "conButtonPaddingY",
        "conButtonRoundness",
        "conButtonBorder",
        "conDescX",
        "conDescY",
        "conWidth",
      ],
      defaults: {
        desktop: {
          conX: 4.18,
          conY: -3.03,
          conButtonX: -5,
          conButtonY: 0.03,
          conButtonScale: 1,
          conButtonPaddingX: 0.35,
          conButtonPaddingY: 0.2,
          conButtonRoundness: 0.06,
          conButtonBorder: 0.005,
          conDescX: -4.98,
          conDescY: -0.29,
          conWidth: 2.07,
        },
        tablet: {
          conX: 0,
          conY: -3.2,
          conButtonX: 0,
          conButtonY: 0.2,
          conButtonScale: 1,
          conButtonPaddingX: 0.2,
          conButtonPaddingY: 0.1,
          conButtonRoundness: 0.1,
          conButtonBorder: 0.008,
          conDescX: 0,
          conDescY: -0.3,
          conWidth: 2.5,
        },
        mobile: {
          conX: 0,
          conY: -3.2,
          conButtonX: 0,
          conButtonY: 0.2,
          conButtonScale: 1,
          conButtonPaddingX: 0.2,
          conButtonPaddingY: 0.1,
          conButtonRoundness: 0.1,
          conButtonBorder: 0.008,
          conDescX: 0,
          conDescY: -0.3,
          conWidth: 2.5,
        },
      },
      ranges: {
        conX: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        conY: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        conButtonX: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        conButtonY: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        conButtonScale: {
          min: 0.1,
          max: 3,
          step: 0.01,
        },
        conButtonPaddingX: {
          min: 0,
          max: 1,
          step: 0.01,
        },
        conButtonPaddingY: {
          min: 0,
          max: 1,
          step: 0.01,
        },
        conButtonRoundness: {
          min: 0,
          max: 0.5,
          step: 0.01,
        },
        conButtonBorder: {
          min: 0.001,
          max: 0.05,
          step: 0.001,
        },
        conDescX: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        conDescY: {
          min: -5,
          max: 5,
          step: 0.01,
        },
        conWidth: {
          min: 0,
          max: 3,
          step: 0.01,
        },
      },
    },
    grid: {
      section: "Grid",
      properties: ["sidePadding", "gridVisible"],
      defaults: {
        desktop: {
          sidePadding: 0.8,
          gridVisible: true,
        },
        tablet: {
          sidePadding: 0.8,
          gridVisible: true,
        },
        mobile: {
          sidePadding: 0.8,
          gridVisible: true,
        },
      },
      ranges: {
        sidePadding: {
          min: 0.1,
          max: 2,
          step: 0.01,
        },
        gridVisible: {
          min: false,
          max: true,
          step: true,
        },
      },
    },
    noise: {
      section: "Noise",
      properties: [
        "noiseScale",
        "noiseSpeed",
        "noiseThreshold",
        "noiseTransition",
        "baseDistortion",
        "strongDistortion",
        "aberrationStrength",
        "aberrationLayers",
        "aberrationSlide",
        "effectDuration",
        "fbmOctaves",
      ],
      defaults: {
        desktop: {
          noiseScale: 1.5,
          noiseSpeed: 0.2,
          noiseThreshold: 0.5,
          noiseTransition: 0.15,
          baseDistortion: 0.09,
          strongDistortion: 0.45,
          aberrationStrength: 0.01,
          aberrationLayers: 4,
          aberrationSlide: 0.12,
          effectDuration: 1.4,
          fbmOctaves: 3,
        },
        tablet: {
          noiseScale: 1.5,
          noiseSpeed: 0.2,
          noiseThreshold: 0.5,
          noiseTransition: 0.15,
          baseDistortion: 0.09,
          strongDistortion: 0.45,
          aberrationStrength: 0.01,
          aberrationLayers: 4,
          aberrationSlide: 0.12,
          effectDuration: 1.4,
          fbmOctaves: 3,
        },
        mobile: {
          noiseScale: 1.5,
          noiseSpeed: 0.2,
          noiseThreshold: 0.5,
          noiseTransition: 0.15,
          baseDistortion: 0.09,
          strongDistortion: 0.45,
          aberrationStrength: 0.01,
          aberrationLayers: 4,
          aberrationSlide: 0.12,
          effectDuration: 1.4,
          fbmOctaves: 3,
        },
      },
      ranges: {
        noiseScale: {
          min: 0.5,
          max: 3,
          step: 0.1,
        },
        noiseSpeed: {
          min: 0,
          max: 1,
          step: 0.01,
        },
        noiseThreshold: {
          min: 0.3,
          max: 0.7,
          step: 0.05,
        },
        noiseTransition: {
          min: 0.05,
          max: 0.3,
          step: 0.05,
        },
        baseDistortion: {
          min: 0.01,
          max: 0.2,
          step: 0.01,
        },
        strongDistortion: {
          min: 0.1,
          max: 0.5,
          step: 0.05,
        },
        aberrationStrength: {
          min: 0.001,
          max: 0.01,
          step: 0.001,
        },
        aberrationLayers: {
          min: 1,
          max: 5,
          step: 1,
        },
        aberrationSlide: {
          min: 0.01,
          max: 2,
          step: 0.01,
        },
        effectDuration: {
          min: 0.2,
          max: 2,
          step: 0.1,
        },
        fbmOctaves: {
          min: 1,
          max: 8,
          step: 1,
        },
      },
    },
  },
  footer: {
    section: "Footer",
    properties: [
      "footerY",
      "footerNavY",
      "footerNavX",
      "footerNavWorkX",
      "footerNavExpertiseX",
      "footerNavAboutX",
      "footerNavPlaygroundX",
      "footerLogoX",
      "footerLogoY",
      "footerCHX",
      "footerCHY",
      "footerCHScale",
      "footerCX",
      "footerHX",
      "footerContactY",
      "footerContactEmailX",
      "footerAddressX",
      "footerAddressY",
      "footerSocialX",
      "footerLegalX",
      "footerTextX",
      "footerTextY",
      "footerTextFont",
      "footerAddressY",
      "footerEmailY",
      "footerSocialY",
      "footerLegalY",
    ],
    defaults: {
      desktop: {
        footerY: -4.25,
        footerNavY: 0.46,
        footerNavX: -0.06,
        footerNavWorkX: 0.02,
        footerNavExpertiseX: 0.27,
        footerNavAboutX: 0.66,
        footerNavPlaygroundX: 0.99,
        footerLogoX: 3.86,
        footerLogoY: 1,
        footerCHX: 0.23,
        footerCHY: 0.33,
        footerCHScale: 0.002,
        footerCX: -0.28,
        footerHX: 0.22,
        footerContactY: -0.5,
        footerContactEmailX: 0.2,
        footerAddressX: -0.08,
        footerAddressY: 0.14,
        footerSocialX: 0.6,
        footerLegalX: 0.85,
        footerTextX: 0,
        footerTextY: -0.06,
        footerTextFont: 0.022,
        footerEmailY: 0.16,
        footerSocialY: 0.18,
        footerLegalY: 0.18,
      },
      tablet: {
        footerY: -4.2,
        footerNavY: 0.4,
        footerNavX: -0.06,
        footerNavWorkX: 0,
        footerNavExpertiseX: 0.33,
        footerNavAboutX: 0.66,
        footerNavPlaygroundX: 0.99,
        footerLogoX: 3.92,
        footerLogoY: -0.69,
        footerCHX: 0.23,
        footerCHY: 0.27,
        footerCHScale: 0.002,
        footerCX: -0.22,
        footerHX: 0.22,
        footerContactY: -0.5,
        footerContactEmailX: 0.2,
        footerAddressX: -0.08,
        footerAddressY: -0.03,
        footerSocialX: 0.6,
        footerLegalX: 0.85,
        footerTextX: 0,
        footerTextY: -0.06,
        footerTextFont: 0.022,
        footerEmailY: -0.06,
        footerSocialY: -0.06,
        footerLegalY: -0.06,
      },
      mobile: {
        footerY: -4.2,
        footerNavY: 0.4,
        footerNavX: -0.06,
        footerNavWorkX: 0,
        footerNavExpertiseX: 0.33,
        footerNavAboutX: 0.66,
        footerNavPlaygroundX: 0.99,
        footerLogoX: 3.92,
        footerLogoY: -0.69,
        footerCHX: 0.23,
        footerCHY: 0.27,
        footerCHScale: 0.002,
        footerCX: -0.22,
        footerHX: 0.22,
        footerContactY: -0.5,
        footerContactEmailX: 0.2,
        footerAddressX: -0.08,
        footerAddressY: -0.03,
        footerSocialX: 0.6,
        footerLegalX: 0.85,
        footerTextX: 0,
        footerTextY: -0.06,
        footerTextFont: 0.022,
        footerEmailY: -0.06,
        footerSocialY: -0.06,
        footerLegalY: -0.06,
      },
    },
    ranges: {
      footerY: {
        min: -10,
        max: 0,
        step: 0.01,
      },
      footerNavY: {
        min: -2,
        max: 2,
        step: 0.01,
      },
      footerNavX: {
        min: -2,
        max: 2,
        step: 0.01,
      },
      footerNavWorkX: {
        min: -2,
        max: 2,
        step: 0.01,
      },
      footerNavExpertiseX: {
        min: -2,
        max: 2,
        step: 0.01,
      },
      footerNavAboutX: {
        min: -2,
        max: 2,
        step: 0.01,
      },
      footerNavPlaygroundX: {
        min: -2,
        max: 2,
        step: 0.01,
      },
      footerLogoX: {
        min: 0,
        max: 5,
        step: 0.01,
      },
      footerLogoY: {
        min: -2,
        max: 2,
        step: 0.01,
      },
      footerCHX: {
        min: -2,
        max: 2,
        step: 0.01,
      },
      footerCHY: {
        min: -2,
        max: 2,
        step: 0.01,
      },
      footerCHScale: {
        min: 0,
        max: 0.01,
        step: 0.0001,
      },
      footerCX: {
        min: -2,
        max: 2,
        step: 0.01,
      },
      footerHX: {
        min: -2,
        max: 2,
        step: 0.01,
      },
      footerContactY: {
        min: -2,
        max: 2,
        step: 0.01,
      },
      footerContactEmailX: {
        min: -2,
        max: 2,
        step: 0.01,
      },
      footerAddressX: {
        min: -2,
        max: 2,
        step: 0.01,
      },
      footerAddressY: {
        min: -2,
        max: 2,
        step: 0.01,
      },
      footerSocialX: {
        min: -2,
        max: 2,
        step: 0.01,
      },
      footerLegalX: {
        min: -2,
        max: 2,
        step: 0.01,
      },
      footerTextX: {
        min: -2,
        max: 2,
        step: 0.01,
      },
      footerTextY: {
        min: -2,
        max: 2,
        step: 0.01,
      },
      footerTextFont: {
        min: 0,
        max: 0.1,
        step: 0.001,
      },
      footerEmailY: {
        min: -2,
        max: 2,
        step: 0.01,
      },
      footerSocialY: {
        min: -2,
        max: 2,
        step: 0.01,
      },
      footerLegalY: {
        min: -2,
        max: 2,
        step: 0.01,
      },
    },
  },
}
